### ISSUE TITLE
handle the (java) exceptions for non-images

### ISSUE THREAD

**Issue by hornig** [aerospaceresearch/gcp-osm#1]
https://github.com/aerospaceresearch/gcp-osm/blob/107822089d88af285e640fdf14cf342c3c8de351/main.py#L16-L18

when non-image files are given to the barcode reader, it thows java exceptions.

handle the exceptions, or filter out non-image files.

if there is no qr-code in a photo, the barcode reader returns "None". Maybe also return "None" here to use the same functions later own.

**Comment by ulip** [comment]
I think the exceptions cannot be handled in our code. The zxing wrapper must detect the failure of the Java function and raise a proper Python exception.

Looking into the [python-zxing](https://github.com/dlenski/python-zxing/blob/f783c0ef77b610b9b6a361745cca6555b32a7bef/zxing/__init__.py#L40) code they seem to try to catch the process failure before the return (by checking the return code of the process) but this seems to be too late already.

**Comment by domyos** [comment]
We no longer use python-zxing so no more java exceptions
